### ISSUE TITLE
Form blank when running. Normal?

### ISSUE THREAD

**Issue by KumariAshamaki** [CodingByHarry/scum_game_bot_os#1]
Hey, I got the bot working fine but as it's running I get an empty form1 that opens a few seconds in. Is this normal or is something meant to be displayed here? If it's normal is it possible to add something here such as the output or to just convert the Form1 to a console? I would have tried myself but there seems to be no form present to edit in visual studio.

**Comment by CodingByHarry** [comment]
Sorry no clue, I don't remember :)

**Comment by KumariAshamaki** [comment]
Lol indeed such is life. Either way it appears to be functioning properly.
